# Generated by Django 5.0.12 on 2025-07-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_subscriber_alter_category_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('private', 'private'), ('public', 'public')], default='public', max_length=10),
        ),
    ]
