# Generated by Django 5.0.12 on 2025-07-22 13:01

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_post_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteCategory',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('note_title', models.CharField(max_length=100)),
                ('add_to', models.DateField(auto_now_add=True, null=True)),
                ('note_image', models.ImageField(upload_to='Note_category')),
                ('url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NotePost',
            fields=[
                ('note_post_id', models.AutoField(primary_key=True, serialize=False)),
                ('note_post_title', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('note_post_des', tinymce.models.HTMLField(max_length=200)),
                ('note_file', models.FileField(upload_to='notes_post/')),
                ('add_to_date', models.DateField(auto_now_add=True, null=True)),
                ('note_post_image', models.ImageField(upload_to='Note_post/')),
                ('status', models.CharField(choices=[('private', 'private'), ('public', 'public')], default='public', max_length=10)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.notecategory')),
            ],
        ),
    ]
