# Generated by Django 5.0.12 on 2025-07-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_notecategory_notepost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_form',
            fields=[
                ('cont_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('messages', models.CharField(max_length=300)),
            ],
        ),
    ]
